### ISSUE TITLE
[Bug]: 无法执行指令

### ISSUE THREAD

**Issue by yyhhkya** [CoderKuo/TrMenu#121]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

```
TrMenu Dump Information (Date: 2024-12-04 00:44:01)

| Server OS: Linux amd64 5.4.0-137-generic
| Server software: 1.20.6-DEV-9a19e42 (MC: 1.20.6) (1.20.6-R0.1-SNAPSHOT)
| Java version: 21.0.5

| TrMenu: 3.3.5e
Installed Plugins: 
· AuthMe - 5.7.0-FORK-b53 (0 KB)
· AxTrade - 1.9.0 (0 KB)
· Backuper - 3.1.1 (0 KB)
· Bolt - 1.1.23 (0 KB)
· CMI - 9.7.6.7 (0 KB)
· CMIEInjector - 1.0.2.4 (0 KB)
· CMILib - 1.5.2.1 (0 KB)
· ChestShop - 3.12.3-SNAPSHOT (build 423) (0 KB)
· CoreProtect - 22.4 (0 KB)
· EpicGuard - 7.6.0 (0 KB)
· FKeepInventoryPro - 1.0 (0 KB)
· FancyNpcs - 2.4.0 (0 KB)
· FastAfdPay - 1.0.2 (0 KB)
· FreedomChat - 1.6.1 (0 KB)
· GSit - 1.11.0 (0 KB)
· InventoryRollbackPlus - 1.6.17 (0 KB)
· LightAntiCheat - 1.2.6 (0 KB)
· LuckPerms - 5.4.141 (0 KB)
· MineBBSTopper - 7.2 (0 KB)
· NBTAPI - 2.14.0 (0 KB)
· PlaceholderAPI - 2.11.7-DEV-null (0 KB)
· Plan - 5.6 build 2883 (0 KB)
· PlayerIntensify - 3.0.2 (0 KB)
· PlayerMenu - 1.3.7 (0 KB)
· PlayerPoints - 3.2.7 (0 KB)
· PlayerTask - 2.3.3 (0 KB)
· PlayerTitle - 4.2.1 (0 KB)
· PlayerWarp - 1.4.6 (0 KB)
· ProtocolLib - 5.3.0 (0 KB)
· Residence - 5.1.6.3 (0 KB)
· SkinsRestorer - 15.4.4 (0 KB)
· TAB - 5.0.1 (0 KB)
· TrMenu - 3.3.5e (0 KB)
· UltimateAutoRestart - 2024.07 (0 KB)
· UltimateShop - 3.1.1 (0 KB)
· Vault - 1.7.3-b0-folia (0 KB)
· WorldEdit - 7.3.9-SNAPSHOT+eb3bb04-Folia (0 KB)
· yeeeesmotd - 1.4.1 (0 KB)
```

### 🔍 Detailed description

```
无法执行命令
```

### 🗄 Server log

```
[00:42:22 WARN]: [TrMenu] Global task for TrMenu v3.3.5e generated an exception
java.lang.IllegalStateException: Dispatching command async
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1018) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1099) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at [T][菜单]TrMenu-3.3.5e.jar/me.arasple.mc.trmenu.taboolib.platform.type.BukkitCommandSender.dispatchCommand(BukkitCommandSender.kt:52) ~[[T][菜单]TrMenu-3.3.5e.jar:?]
        at [T][菜单]TrMenu-3.3.5e.jar/me.arasple.mc.trmenu.taboolib.platform.type.BukkitCommandSender.performCommand(BukkitCommandSender.kt:40) ~[[T][菜单]TrMenu-3.3.5e.jar:?]
        at [T][菜单]TrMenu-3.3.5e.jar/me.arasple.mc.trmenu.taboolib.platform.type.BukkitPlayer.performCommand(BukkitPlayer.kt:394) ~[[T][菜单]TrMenu-3.3.5e.jar:?]
        at [T][菜单]TrMenu-3.3.5e.jar/me.arasple.mc.trmenu.api.action.impl.send.Command.onExecute$lambda$1$lambda$0(Command.kt:23) ~[[T][菜单]TrMenu-3.3.5e.jar:?]
        at [T][菜单]TrMenu-3.3.5e.jar/me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$FoliaRunningTask.execute$lambda$8(BukkitExecutor.kt:150) ~[[T][菜单]TrMenu-3.3.5e.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.6.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.6.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

```

### ⚙ Configurations

```
    actions:
      all: 
        - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
        - 'close'
      left:
        - 'command: ping'
```

**Comment by CoderKuo** [comment]
3.3.8版本已处理
