### ISSUE TITLE
[问题]: 1.12.2 无法打开菜单

### ISSUE THREAD

**Issue by xinyihl** [CoderKuo/TrMenu#124]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2024-12-05 23:40:25)

| Server OS: Windows 11 amd64 10.0
| Server software: git-CatServer-1.12.2-5a600445 (MC: 1.12.2) (1.12.2-R0.1-SNAPSHOT)
| Java version: 1.8.0_361

| TrMenu: 3.3.5e
Installed Plugins:
· PlaceholderAPI - 2.11.2 (0 KB)
· TrMenu - 3.3.5e (0 KB)
· spark - 1.8.19 (0 KB)
```

### 🔍 详细的描述

```
1. 安装最新插件
2. 打开任意默认菜单
```

### 🗄 服务端日志

```
[23:41:39] [pool-15-thread-1/WARN]: java.lang.ClassNotFoundException: vg
[23:41:39] [pool-15-thread-1/WARN]:     at java.lang.Class.forName0(Native Method)
[23:41:39] [pool-15-thread-1/WARN]:     at java.lang.Class.forName(Unknown Source)
[23:41:39] [pool-15-thread-1/WARN]:     at catserver.server.remapper.target.ReflectionMethods.forName(ReflectionMethods.java:37)
[23:41:39] [pool-15-thread-1/WARN]:     at catserver.server.remapper.target.ReflectionMethods.forName(ReflectionMethods.java:17)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.ClassAnalyser.analyseByASM$lambda$6(ClassAnalyser.kt:64)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.LazyClass$Companion.of$lambda$5(LazyClass.kt:118)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.LazyClass$instance$2.invoke(LazyClass.kt:26)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.LazyClass$instance$2.invoke(LazyClass.kt:25)
[23:41:39] [pool-15-thread-1/WARN]:     at kotlin2020.UnsafeLazyImpl.getValue(Lazy.kt:81)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.LazyClass.getInstance(LazyClass.kt:25)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.ClassField.getFieldType(ClassField.kt:22)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassField.get(JavaClassField.kt:27)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.Reflex$Companion._get(Reflex.kt:147)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:97)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.Reflex$Companion.getProperty$default(Reflex.kt:87)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.module.nms.PacketSender.getConnection(PacketSender.kt:94)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.module.nms.PacketSender.sendPacket(PacketSender.kt:67)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.module.nms.MinecraftServerUtilKt.sendPacketBlocking(MinecraftServerUtil.kt:209)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.module.nms.MinecraftServerUtilKt.sendPacket$lambda$5(MinecraftServerUtil.kt:174)
[23:41:39] [pool-15-thread-1/WARN]:     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[23:41:39] [pool-15-thread-1/WARN]:     at java.util.concurrent.FutureTask.run(Unknown Source)
[23:41:39] [pool-15-thread-1/WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[23:41:39] [pool-15-thread-1/WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[23:41:39] [pool-15-thread-1/WARN]:     at java.lang.Thread.run(Unknown Source)
```

### ⚙ 配置文件

默认配置&菜单

**Comment by xinyihl** [comment]
是 taboolib 6.2 的问题，我自己构建了一份 6.1 的没问题

**Comment by aeroidesdev** [comment]
那么,你该去给taboolib 提而不是 TrMenu

**Comment by xANoyU** [comment]
> 是 taboolib 6.2 的问题，我自己构建了一份 6.1 的没问题

怎么弄啊求助

**Comment by xinyihl** [comment]
最新版本 taboolib 修了，等 trmenu 更新吧

好吧并没有修复，看着有一个相关的提交以为修了呢。

**Comment by xANoyU** [comment]
https://github.com/Dreeam-qwq/TrMenu/actions/runs/12763071985
最新的3.3.7打开菜单仍然报错
[报错.log](https://github.com/user-attachments/files/18408296/default.log)

**Comment by Bkm016** [comment]
```
[23:41:39] [pool-15-thread-1/WARN]: java.lang.ClassNotFoundException: vg
[23:41:39] [pool-15-thread-1/WARN]:     at java.lang.Class.forName0(Native Method)
[23:41:39] [pool-15-thread-1/WARN]:     at java.lang.Class.forName(Unknown Source)
[23:41:39] [pool-15-thread-1/WARN]:     at catserver.server.remapper.target.ReflectionMethods.forName(ReflectionMethods.java:37)
[23:41:39] [pool-15-thread-1/WARN]:     at catserver.server.remapper.target.ReflectionMethods.forName(ReflectionMethods.java:17)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.ClassAnalyser.analyseByASM$lambda$6(ClassAnalyser.kt:64)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.LazyClass$Companion.of$lambda$5(LazyClass.kt:118)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.LazyClass$instance$2.invoke(LazyClass.kt:26)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.LazyClass$instance$2.invoke(LazyClass.kt:25)
[23:41:39] [pool-15-thread-1/WARN]:     at kotlin2020.UnsafeLazyImpl.getValue(Lazy.kt:81)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.LazyClass.getInstance(LazyClass.kt:25)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.ClassField.getFieldType(ClassField.kt:22)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassField.get(JavaClassField.kt:27)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.Reflex$Companion._get(Reflex.kt:147)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:97)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.library.reflex.Reflex$Companion.getProperty$default(Reflex.kt:87)
[23:41:39] [pool-15-thread-1/WARN]:     at me.arasple.mc.trmenu.taboolib.module.nms.PacketSender.getConnection(PacketSender.kt:94)
```

我猜测是 asm 模式不支持在 hybrid 服务端下运行

**Comment by Bkm016** [comment]
因为 6.1 是反射模式，hybrid 会处理

**Comment by XiaoJie-150** [comment]
使用了6.2.3导致的,6.2.2可以正常跑

**Comment by YsGqHY** [comment]
已支持，更新TrMenu至最新版 3.9.10
