### ISSUE TITLE
[问题]:  Spigot 1.20.2 菜单无法显示玩家头颅

### ISSUE THREAD

**Issue by BiliRumble** [CoderKuo/TrMenu#17]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2023-12-05 18:58:43)

| Server OS: Windows Server 2019 amd64 10.0
| Server software: 3926-Spigot-dba3cdc-ffb1319 (MC: 1.20.2) (1.20.2-R0.1-SNAPSHOT)
| Java version: 17.0.9

| TrMenu: 3.1.29-SNAPSHOT
Installed Plugins: 
· BetterRTP - 3.6.10 (0 KB)
· CMI - 9.6.7.5 (0 KB)
· CMILib - 1.4.3.5 (0 KB)
· Citizens - 2.0.33-SNAPSHOT (build 3250) (0 KB)
· CoreProtect - 22.1 (0 KB)
· CrazyAuctionsPlus - 1.3.3.0 (0 KB)
· DeluxeTags - 1.8.3-DEV-23 (0 KB)
· DivineDrop - 2.13 (0 KB)
· GemsEconomy - 4.9.3-GCRemake-1.6 (0 KB)
· JoinCommands - 2.1 (0 KB)
· JulyLibrary - 2.4.4 (0 KB)
· JulySafe - 2.0.0-beta3 (0 KB)
· LiteBans - 2.12.5 (0 KB)
· LiteSignIn - 1.8.0.1 (0 KB)
· LuckPerms - 5.4.40 (0 KB)
· MiaoBoard - 2.6.0-git-00db90be472bcc688847491a33f195cc5637bbd1 (0 KB)
· Multiverse-Core - 4.3.1-b861 (0 KB)
· NBTAPI - 2.12.0 (0 KB)
· PVPMode - 1.5 (0 KB)
· PlaceholderAPI - 2.11.3 (0 KB)
· PlayerPoints - 2.1.8 (0 KB)
· PlugMan - 2.1.7 (0 KB)
· QuickShop - 5.1.2.5 (0 KB)
· Residence - 5.0.1.6 (0 KB)
· ResourceWorld - 2.0.2 (0 KB)
· Shopkeepers - 2.12.0 (0 KB)
· SimpleHomes - 2.0.4 (0 KB)
· SkinsRestorer - 15.0.3 (0 KB)
· TrChat - 2.0.9 (0 KB)
· TrMenu - 3.1.29-SNAPSHOT (0 KB)
· Vault - 1.7.3-CMI (0 KB)
· ViaBackwards - 4.8.1 (0 KB)
· ViaVersion - 4.8.1 (0 KB)
· floodgate - 2.2.2-SNAPSHOT (b95-71acc6c) (0 KB)
· mcMMO - 2.1.217 (0 KB)
```

### 🔍 详细的描述

```
1. 打开菜单报错
2. 使用%player_name%的玩家头颅不显示
```

### 🗄 服务端日志

```
[19:00:32] [Server thread/WARN]: java.lang.IllegalArgumentException: Attempt to get boolean field "net.minecraft.server.level.EntityPlayer.f
" with illegal data type conversion to int
[19:00:32] [Server thread/WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.newGetIllegalArgumentException(UnsafeField
AccessorImpl.java:69)
[19:00:32] [Server thread/WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.newGetIntIllegalArgumentException(UnsafeFi
eldAccessorImpl.java:132)
[19:00:32] [Server thread/WARN]:        at java.base/jdk.internal.reflect.UnsafeBooleanFieldAccessorImpl.getInt(UnsafeBooleanFieldAccessorIm
pl.java:57)
[19:00:32] [Server thread/WARN]:        at java.base/java.lang.reflect.Field.getInt(Field.java:601)
[19:00:32] [Server thread/WARN]:        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:66)
[19:00:32] [Server thread/WARN]:        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:50)
[19:00:32] [Server thread/WARN]:        at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:131)
[19:00:32] [Server thread/WARN]:        at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:481)
[19:00:32] [Server thread/WARN]:        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:403)
[19:00:32] [Server thread/WARN]:        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[19:00:32] [Server thread/WARN]:        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[19:00:32] [Server thread/WARN]:        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.taboolib.platform.compat.PlaceholderExpansionKt.replacePlaceholder(Placehold
erExpansion.kt:21)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.module.display.MenuSession.parse(MenuSession.kt:116)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.module.display.item.Lore.parse(Lore.kt:32)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.module.display.item.Item.lore(Item.kt:28)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.module.display.item.Item.build$default(Item.kt:63)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.module.display.item.Item.get(Item.kt:32)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:80)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.module.display.icon.Icon.filter(Icon.kt:156)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.module.display.icon.Icon.onRefresh(Icon.kt:85)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.module.display.Menu.loadIcon(Menu.kt:155)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.module.display.Menu.open(Menu.kt:90)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.module.display.Menu.open$default(Menu.kt:48)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.module.internal.listener.ListenerCommand.onCommand(ListenerCommand.kt:25)
[19:00:32] [Server thread/WARN]:        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:
77)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:
76)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke
(Listener.kt:39)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke
(Listener.kt:39)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitLi
stener.kt:36)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitLi
stener.kt:36)
[19:00:32] [Server thread/WARN]:        at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:73
)
[19:00:32] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:00:32] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[19:00:32] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[19:00:32] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1803)
[19:00:32] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$15(PlayerConnection.java:1789)
[19:00:32] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67)
[19:00:32] [Server thread/WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[19:00:32] [Server thread/WARN]:        at net.minecraft.server.TickTask.run(SourceFile:18)
[19:00:32] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156)
[19:00:32] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[19:00:32] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1133)
[19:00:32] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
[19:00:32] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130)
[19:00:32] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1112)
[19:00:32] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1105)
[19:00:32] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139)
[19:00:32] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1089)
[19:00:32] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000)
[19:00:32] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298)
[19:00:32] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[19:00:32] [Server thread/INFO]: ICON: A
```

### ⚙ 配置文件

```
'A':
    update: 6
    display:
      mats: 'head:%player_name%'
      name:
        - '&6&l欢迎你, &e&l%player_name%'
      lore:
        - - ''
          - '&7你的个人信息'
          - ''
          - '&8▪ &7ID: &e%player_name%'
          - '&8▪ &7组别: &r%luckperms_lowest_group_by_weight%'
          - '&8▪ &7延迟: &b%player_ping% MS'
          - '&8▪ &7等级: &aLv.%player_level%'
          - '&8▪ &7饱食度: &6%player_food_level%'
          - '&8▪ &7血量: &c%player_health_rounded% ❤'
          - '&8▪ &7位置: &2%player_world%, &b%player_x%/%player_y%/%player_z%'
          - ''
          - '&b左键 &a➥ &6倒数5秒发射你自己 :`'
          - '&b右键 &a➥ &6直接发射 :`'
      amount: '1'
    actions:
      all: ['sound: BLOCK_NOTE_BLOCK_PLING-1-2']
      left:
        - 'close'
        - 'title: `&a&l准备好了吗, &b&l%player_name%` `&7&l你即将弹射升空...`'
        - 'wait: 25'
        - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
        - 'title: `&2&l5s`'
        - 'wait: 25'
        - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
        - 'title: `&3&l4s`'
        - 'wait: 25'
        - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
        - 'title: `&b&l3s`'
        - 'wait: 25'
        - 'sound: BLOCK_NOTE_BLOCK_PLING-1-1'
        - 'title: `&6&l2s`'
        - 'wait: 25'
        - 'sound: BLOCK_NOTE_BLOCK_PLING-1-0'
        - 'title: `&4&l1s`'
        - 'wait: 25'
        - 'sound: ENTITY_FIREWORK_ROCKET_LAUNCH-2-1'
        - 'title: `&6&lWoooooooo!` `&a&l不出意外你弹射了很高~`'
        - 'js: player.setVelocity(player.getVelocity().setY(15))'
        - 'js: player.setNoDamageTicks(20*10)'
      right:
        - 'close'
        - 'sound: ENTITY_FIREWORK_ROCKET_LAUNCH-2-1'
        - 'title: `&6&lWoooooooo!` `&a&l不出意外你弹射了很高~`'
        - 'js: player.setVelocity(player.getVelocity().setY(15))'
        - 'js: player.setNoDamageTicks(20*10)'
```

**Comment by Dreeam-qwq** [comment]
报错不是TrMenu的问题，请更新你的Player papi变量扩展和papi
https://api.extendedclip.com/expansions/player/

另外1.20.2无法显示头颅是已知问题https://github.com/Dreeam-qwq/TrMenu/issues/13
