### ISSUE TITLE
[问题]: Spigot 1.20.2打开菜单后重复报错

### ISSUE THREAD

**Issue by BiliRumble** [CoderKuo/TrMenu#18]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2023-12-05 18:58:43)

| Server OS: Windows Server 2019 amd64 10.0
| Server software: 3926-Spigot-dba3cdc-ffb1319 (MC: 1.20.2) (1.20.2-R0.1-SNAPSHOT)
| Java version: 17.0.9

| TrMenu: 3.1.29-SNAPSHOT
Installed Plugins: 
· BetterRTP - 3.6.10 (0 KB)
· CMI - 9.6.7.5 (0 KB)
· CMILib - 1.4.3.5 (0 KB)
· Citizens - 2.0.33-SNAPSHOT (build 3250) (0 KB)
· CoreProtect - 22.1 (0 KB)
· CrazyAuctionsPlus - 1.3.3.0 (0 KB)
· DeluxeTags - 1.8.3-DEV-23 (0 KB)
· DivineDrop - 2.13 (0 KB)
· GemsEconomy - 4.9.3-GCRemake-1.6 (0 KB)
· JoinCommands - 2.1 (0 KB)
· JulyLibrary - 2.4.4 (0 KB)
· JulySafe - 2.0.0-beta3 (0 KB)
· LiteBans - 2.12.5 (0 KB)
· LiteSignIn - 1.8.0.1 (0 KB)
· LuckPerms - 5.4.40 (0 KB)
· MiaoBoard - 2.6.0-git-00db90be472bcc688847491a33f195cc5637bbd1 (0 KB)
· Multiverse-Core - 4.3.1-b861 (0 KB)
· NBTAPI - 2.12.0 (0 KB)
· PVPMode - 1.5 (0 KB)
· PlaceholderAPI - 2.11.3 (0 KB)
· PlayerPoints - 2.1.8 (0 KB)
· PlugMan - 2.1.7 (0 KB)
· QuickShop - 5.1.2.5 (0 KB)
· Residence - 5.0.1.6 (0 KB)
· ResourceWorld - 2.0.2 (0 KB)
· Shopkeepers - 2.12.0 (0 KB)
· SimpleHomes - 2.0.4 (0 KB)
· SkinsRestorer - 15.0.3 (0 KB)
· TrChat - 2.0.9 (0 KB)
· TrMenu - 3.1.29-SNAPSHOT (0 KB)
· Vault - 1.7.3-CMI (0 KB)
· ViaBackwards - 4.8.1 (0 KB)
· ViaVersion - 4.8.1 (0 KB)
· floodgate - 2.2.2-SNAPSHOT (b95-71acc6c) (0 KB)
· mcMMO - 2.1.217 (0 KB)
```

### 🔍 详细的描述

在上一个反馈的BUG( #17  )后控制台报错刷屏

### 🗄 服务端日志

```
[19:00:33] [Craft Scheduler Thread - 10/WARN]: [TrMenu] Plugin TrMenu v3.1.29-SNAPSHOT generated an exception while executing task 2169
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2086) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4012) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4922) ~[guava-32.1.2-jre.jar:?]
        at com.extendedclip.papi.expansion.server.ServerExpansion.getCached(ServerExpansion.java:115) ~[?:?]
        at com.extendedclip.papi.expansion.server.ServerExpansion.onRequest(ServerExpansion.java:199) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.compat.PlaceholderExpansionKt.replacePlaceholder(PlaceholderExpansion.kt:21) ~[?:?]
        at me.arasple.mc.trmenu.module.display.MenuSession.parse(MenuSession.kt:116) ~[?:?]
        at me.arasple.mc.trmenu.module.display.item.Lore.parse(Lore.kt:32) ~[?:?]
        at me.arasple.mc.trmenu.module.display.item.Item.lore(Item.kt:28) ~[?:?]
        at me.arasple.mc.trmenu.module.display.item.Item.access$lore(Item.kt:17) ~[?:?]
        at me.arasple.mc.trmenu.module.display.item.Item$updateLore$new$1.invoke(Item.kt:109) ~[?:?]
        at me.arasple.mc.trmenu.module.display.item.Item$updateLore$new$1.invoke(Item.kt:107) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.util.ItemBuilderKt.buildItem(ItemBuilder.kt:50) ~[?:?]
        at me.arasple.mc.trmenu.module.display.item.Item.updateLore(Item.kt:107) ~[?:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.onUpdate(Icon.kt:65) ~[?:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:27) ~[?:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:26) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$2.run(BukkitExecutor.kt:52) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3926-Spigot-dba3cdc-
ffb1319]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3926-Spigo
t-dba3cdc-ffb1319]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3926-Spigot-dba3cdc-ffb1319]
        at net.minecraft.server.level.WorldServer.E(WorldServer.java:1880) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3926-Spigot-dba3cdc-ffb1319]
        at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.getNMSEntities(CraftWorld.java:819) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3926-Spigot-dba3
cdc-ffb1319]
        at org.bukkit.craftbukkit.v1_20_R2.CraftRegionAccessor.getLivingEntities(CraftRegionAccessor.java:469) ~[spigot-1.20.2-R0.1-SNAPSHOT
.jar:3926-Spigot-dba3cdc-ffb1319]
        at com.extendedclip.papi.expansion.server.ServerExpansion.lambda$getLivingEntities$1(ServerExpansion.java:134) ~[?:?]
        at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.IntPipeline.reduce(IntPipeline.java:515) ~[?:?]
        at java.util.stream.IntPipeline.sum(IntPipeline.java:473) ~[?:?]
        at com.extendedclip.papi.expansion.server.ServerExpansion.getLivingEntities(ServerExpansion.java:135) ~[?:?]
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4927) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3571) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2190) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2080) ~[guava-32.1.2-jre.jar:?]
        ... 25 more
```

### ⚙ 配置文件

*好像并没有*

**Comment by Dreeam-qwq** [comment]
更新你的server变量扩展和papi
https://api.extendedclip.com/expansions/server/
