### ISSUE TITLE
[功能]: 支持folia

### ISSUE THREAD

**Issue by xiaoluofa** [CoderKuo/TrMenu#45]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 🔍 详细的描述

如题

### ⚙ 配置文件

```

```

**Comment by TheFloodDragon** [comment]
试过最新版本吗，如有问题贴出报错日志

[TrMenu-3.3.0-SNAPSHOT](https://github.com/Dreeam-qwq/TrMenu/releases/download/trmenu/TrMenu-3.3.0-SNAPSHOT.jar)

**Comment by xiaoluofa** [comment]
data mysql无法跨服同步。子服是1，而另一个服务器读取缺是0，已经配置数据库

**Comment by xiaoluofa** [comment]
打开GUI类操作报错，比如使用按钮触发workbench命令会报错。其他情况也会
[16:04:58 WARN]: [TrMenu] Global task for TrMenu v3.3.0-SNAPSHOT generated an exception
java.lang.IllegalStateException: Dispatching command async
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1032) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1094) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.type.BukkitCommandSender.dispatchCommand(BukkitCommandSender.kt:52) ~[TrMenu-3.3.0-SNAPSHO
T.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.type.BukkitCommandSender.performCommand(BukkitCommandSender.kt:40) ~[TrMenu-3.3.0-SNAPSHOT
.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.type.BukkitPlayer.performCommand(BukkitPlayer.kt:440) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.send.Command$onExecute$1.invoke(Command.kt:24) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.send.Command$onExecute$1.invoke(Command.kt:26) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.send.Command.onExecute(Command.kt:28) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionBase$Option.evalPlayers(ActionBase.kt:115) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry.execute(ActionEntry.kt:31) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.ActionHandle.runAction(ActionHandle.kt:92) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.reaction.Reactions.eval(Reactions.kt:16) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.IconProperty.handleClick(IconProperty.kt:42) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1.invoke(Layout.kt:90) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1.invoke(Layout.kt:89) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$FoliaRunningTask.execute$lambda$8(BukkitExecutor.kt:146) ~[TrMenu-3.3.0-SNA
PSHOT.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179
) ~[luminol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[luminol-1.20.4.j
ar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c
"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[luminol-1.20.4.jar
:git-Luminol-"01abc6c"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.
jar:git-Luminol-"01abc6c"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.j
ar:git-Luminol-"01abc6c"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:04:58 ERROR]: Thread Region Scheduler Thread #17 failed main thread check: Dispatching command async
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1032) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1094) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.type.BukkitCommandSender.dispatchCommand(BukkitCommandSender.kt:52) ~[TrMenu-3.3.0-SNAPSHO
T.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.type.BukkitCommandSender.performCommand(BukkitCommandSender.kt:40) ~[TrMenu-3.3.0-SNAPSHOT
.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.type.BukkitPlayer.performCommand(BukkitPlayer.kt:440) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.send.Command$onExecute$1.invoke(Command.kt:24) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.send.Command$onExecute$1.invoke(Command.kt:26) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.send.Command.onExecute(Command.kt:28) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionBase$Option.evalPlayers(ActionBase.kt:115) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry.execute(ActionEntry.kt:31) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.ActionHandle.runAction(ActionHandle.kt:92) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.reaction.Reactions.eval(Reactions.kt:16) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.IconProperty.handleClick(IconProperty.kt:42) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1.invoke(Layout.kt:90) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1.invoke(Layout.kt:89) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$FoliaRunningTask.execute$lambda$8(BukkitExecutor.kt:146) ~[TrMenu-3.3.0-SNA
PSHOT.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179
) ~[luminol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[luminol-1.20.4.j
ar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c
"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[luminol-1.20.4.jar
:git-Luminol-"01abc6c"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.
jar:git-Luminol-"01abc6c"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.j
ar:git-Luminol-"01abc6c"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by xiaoluofa** [comment]
[16:08:35 ERROR]: Thread Region Scheduler Thread #20 failed main thread check: Dispatching command async
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1032) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1094) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.type.BukkitCommandSender.dispatchCommand(BukkitCommandSender.kt:52) ~[TrMenu-3.3.0-SNAPSHO
T.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.type.BukkitCommandSender.performCommand(BukkitCommandSender.kt:40) ~[TrMenu-3.3.0-SNAPSHOT
.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.type.BukkitPlayer.performCommand(BukkitPlayer.kt:440) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.send.CommandOp$onExecute$1.invoke(CommandOp.kt:27) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.send.CommandOp$onExecute$1.invoke(CommandOp.kt:34) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.send.CommandOp.onExecute(CommandOp.kt:36) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionBase$Option.evalPlayers(ActionBase.kt:115) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry.execute(ActionEntry.kt:31) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.ActionHandle.runAction(ActionHandle.kt:92) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.reaction.Reactions.eval(Reactions.kt:16) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.IconProperty.handleClick(IconProperty.kt:42) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1.invoke(Layout.kt:90) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1.invoke(Layout.kt:89) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$FoliaRunningTask.execute$lambda$8(BukkitExecutor.kt:146) ~[TrMenu-3.3.0-SNA
PSHOT.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179
) ~[luminol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[luminol-1.20.4.j
ar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c
"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[luminol-1.20.4.jar
:git-Luminol-"01abc6c"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.
jar:git-Luminol-"01abc6c"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.j
ar:git-Luminol-"01abc6c"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:08:35 WARN]: java.lang.IllegalStateException: Dispatching command async
[16:08:35 WARN]:        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79)
[16:08:35 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1032)
[16:08:35 WARN]:        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1094)
[16:08:35 WARN]:        at TrMenu-3.3.0-SNAPSHOT.jar//me.arasple.mc.trmenu.taboolib.platform.type.BukkitCommandSender.dispatchCommand(Bukkit
CommandSender.kt:52)
[16:08:35 WARN]:        at TrMenu-3.3.0-SNAPSHOT.jar//me.arasple.mc.trmenu.taboolib.platform.type.BukkitCommandSender.performCommand(BukkitC
ommandSender.kt:40)
[16:08:35 WARN]:        at TrMenu-3.3.0-SNAPSHOT.jar//me.arasple.mc.trmenu.taboolib.platform.type.BukkitPlayer.performCommand(BukkitPlayer.k
t:440)
[16:08:35 WARN]:        at TrMenu-3.3.0-SNAPSHOT.jar//me.arasple.mc.trmenu.api.action.impl.send.CommandOp$onExecute$1.invoke(CommandOp.kt:27
)
[16:08:35 WARN]:        at TrMenu-3.3.0-SNAPSHOT.jar//me.arasple.mc.trmenu.api.action.impl.send.CommandOp$onExecute$1.invoke(CommandOp.kt:34
)
[16:08:35 WARN]:        at TrMenu-3.3.0-SNAPSHOT.jar//me.arasple.mc.trmenu.api.action.impl.send.CommandOp.onExecute(CommandOp.kt:36)
[16:08:35 WARN]:        at TrMenu-3.3.0-SNAPSHOT.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntr
y.kt:29)
[16:08:35 WARN]:        at TrMenu-3.3.0-SNAPSHOT.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntr
y.kt:29)
[16:08:35 WARN]:        at TrMenu-3.3.0-SNAPSHOT.jar//me.arasple.mc.trmenu.api.action.base.ActionBase$Option.evalPlayers(ActionBase.kt:115)
[16:08:35 WARN]:        at TrMenu-3.3.0-SNAPSHOT.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.
kt:29)
[16:08:35 WARN]:        at TrMenu-3.3.0-SNAPSHOT.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.
kt:29)
[16:08:35 WARN]:        at TrMenu-3.3.0-SNAPSHOT.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry.execute(ActionEntry.kt:31)
[16:08:35 WARN]:        at TrMenu-3.3.0-SNAPSHOT.jar//me.arasple.mc.trmenu.api.action.ActionHandle.runAction(ActionHandle.kt:92)
[16:08:35 WARN]:        at TrMenu-3.3.0-SNAPSHOT.jar//me.arasple.mc.trmenu.api.reaction.Reactions.eval(Reactions.kt:16)
[16:08:35 WARN]:        at TrMenu-3.3.0-SNAPSHOT.jar//me.arasple.mc.trmenu.module.display.icon.IconProperty.handleClick(IconProperty.kt:42)
[16:08:35 WARN]:        at TrMenu-3.3.0-SNAPSHOT.jar//me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1.invoke(Layout.kt:
90)
[16:08:35 WARN]:        at TrMenu-3.3.0-SNAPSHOT.jar//me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1.invoke(Layout.kt:
89)
[16:08:35 WARN]:        at TrMenu-3.3.0-SNAPSHOT.jar//me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$FoliaRunningTask.execute$lambda$
8(BukkitExecutor.kt:146)
[16:08:35 WARN]:        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionSc
heduler.java:179)
[16:08:35 WARN]:        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37)
[16:08:35 WARN]:        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293)
[16:08:35 WARN]:        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148)
[16:08:35 WARN]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404)
[16:08:35 WARN]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525)
[16:08:35 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by xiaoluofa** [comment]
[00:14:29 ERROR]: Thread Region Scheduler Thread #0 failed main thread check: Dispatching command async
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1032) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1094) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.type.BukkitCommandSender.dispatchCommand(BukkitCommandSender.kt:52) ~[TrMenu-3.3.0-SNAPSHO
T.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.type.BukkitCommandSender.performCommand(BukkitCommandSender.kt:40) ~[TrMenu-3.3.0-SNAPSHOT
.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.type.BukkitPlayer.performCommand(BukkitPlayer.kt:440) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.send.Command$onExecute$1.invoke(Command.kt:24) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.send.Command$onExecute$1.invoke(Command.kt:26) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.send.Command.onExecute(Command.kt:28) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionBase$Option.evalPlayers(ActionBase.kt:115) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry.execute(ActionEntry.kt:31) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.action.ActionHandle.runAction(ActionHandle.kt:92) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.api.reaction.Reactions.eval(Reactions.kt:16) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.IconProperty.handleClick(IconProperty.kt:42) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1.invoke(Layout.kt:90) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1.invoke(Layout.kt:89) ~[TrMenu-3.3.0-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$FoliaRunningTask.execute$lambda$8(BukkitExecutor.kt:146) ~[TrMenu-3.3.0-SNA
PSHOT.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179
) ~[luminol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[luminol-1.20.4.j
ar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c
"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[luminol-1.20.4.jar
:git-Luminol-"01abc6c"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.
jar:git-Luminol-"01abc6c"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.j
ar:git-Luminol-"01abc6c"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by xiaoluofa** [comment]
所有动作好像都没法运行了

**Comment by xiaoluofa** [comment]
- 'js: vars("%papi-a_var.servername%") == "1obby"' paper 无法比较

**Comment by TheFloodDragon** [comment]
[dfbf7336b0c459706e4587014514e1975d1a4040](https://github.com/Dreeam-qwq/TrMenu/commit/dfbf7336b0c459706e4587014514e1975d1a4040)
已尝试修复指令问题

**Comment by CoderKuo** [comment]
指令问题针对Folia修复了一次 测试一下 8497182cb42f5e0655accae0f067e650c7a4ebc3
