### ISSUE TITLE
[Bug]: 头颅无法正常显示，并且报错，paper

### ISSUE THREAD

**Issue by xiaoluofa** [CoderKuo/TrMenu#54]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

TrMenu Dump Information (Date: 2024-05-02 21:47:28)

| Server OS: Windows 11 amd64 10.0
| Server software: git-Paper-477 (MC: 1.20.4) (1.20.4-R0.1-SNAPSHOT)
| Java version: 21.0.1

| TrMenu: 3.3.0b-SNAPSHOT
Installed Plugins: 
· AntiPopup - 7.3 (0 KB)
· AttributePlus - 3.3.2.6 (0 KB)
· CoreProtect - 22.2 (0 KB)
· CoreTor2 - 5.1.0 (0 KB)
· GSit - 1.9.1 (0 KB)
· GlobalGamerules - 1.0.0 (0 KB)
· GrimAC - 2.3.62 (0 KB)
· HeadDatabase - 4.19.3 (0 KB)
· HexNicks - 3.1.1 (0 KB)
· HolographicDisplays - 3.0.4 (0 KB)
· HuskHomes - 4.6.2 (0 KB)
· InvSync - 2.1.5 (0 KB)
· InventoryRollbackPlus - 1.6.15 (0 KB)
· ItemEdit - 3.1.5 (0 KB)
· KillCommand - 1.0 (0 KB)
· Kotlin - 1.9.23 (0 KB)
· LuckPerms - 5.4.113 (0 KB)
· ModelEngine - R4.0.5 (0 KB)
· Multiverse-Core - 4.3.12 (0 KB)
· Multiverse-NetherPortals - 4.2.3 (0 KB)
· MythicLib - 1.6.2-SNAPSHOT (0 KB)
· MythicMobs - 5.6.1-${CI_COMMIT_SHORT_SHA} (0 KB)
· NBTAPI - 2.12.2 (0 KB)
· Oraxen - 1.173.0 (0 KB)
· PlaceholderAPI - 2.11.5 (0 KB)
· PlayerTitle - 3.5.2 (0 KB)
· PlugManX - 2.3.7 (0 KB)
· ProtocolLib - 5.2.0-SNAPSHOT-679 (0 KB)
· RedisChat - 4.5.0 (0 KB)
· ScriptBlockPlus - 2.2.8 (0 KB)
· TAB-Bridge - 5.0.3 (0 KB)
· TrMenu - 3.3.0b-SNAPSHOT (0 KB)
· UltimateTeams - 2.0.4 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· VoidGen - 2.2.1 (0 KB)
· WorldEdit - 7.3.0-SNAPSHOT+8ddbd3a (0 KB)
· WorldGuard - 7.0.9+5934e49 (0 KB)

### 🔍 Detailed description

头颅无法显示，按钮消失

### 🗄 Server log

[21:45:17 INFO]: ICON: C
[21:45:17 WARN]: java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getValue()'
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.taboolib.platform.util.ItemBuilder.getSkinValue(ItemBuilder.kt:231)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.taboolib.platform.util.ItemBuilder.<init>(ItemBuilder.kt:358)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.taboolib.platform.util.ItemBuilderKt.buildItem(ItemBuilder.kt:47)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.module.display.item.Item.generate(Item.kt:59)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.module.display.item.Item.build(Item.kt:115)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.module.display.item.Item.build$default(Item.kt:110)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.module.display.item.Item.get(Item.kt:38)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:77)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.module.display.icon.Icon.filter(Icon.kt:153)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.module.display.icon.Icon.onRefresh(Icon.kt:82)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.module.display.Menu.loadIcon(Menu.kt:164)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.module.display.Menu.open(Menu.kt:94)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.api.action.impl.menu.Open.onExecute(Open.kt:29)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.api.action.base.ActionBase$Option.evalPlayers(ActionBase.kt:115)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry.execute(ActionEntry.kt:31)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.api.action.ActionHandle.runAction(ActionHandle.kt:92)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.api.reaction.Reactions.eval(Reactions.kt:16)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.module.internal.service.Shortcuts.offhand(Shortcuts.kt:37)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.module.internal.service.Shortcuts.offHand(Shortcuts.kt:123)
[21:45:17 WARN]:        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt
:36)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt
:36)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34
)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34
)
[21:45:17 WARN]:        at TrMenu-3.3.0b-SNAPSHOT.jar//me.arasple.mc.trmenu.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55)
[21:45:17 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[21:45:17 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:45:17 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[21:45:17 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[21:45:17 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[21:45:17 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1785)
[21:45:17 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:42)
[21:45:17 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:15)
[21:45:17 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
[21:45:17 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:45:17 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[21:45:17 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[21:45:17 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1465)
[21:45:17 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[21:45:17 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[21:45:17 WARN]:        at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1442)
[21:45:17 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1365)
[21:45:17 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bu(IAsyncTaskHandler.java:114)
[21:45:17 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1557)
[21:45:17 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[21:45:17 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[21:45:17 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

### ⚙ Configurations

Layout:
- '#        '
Title: Template*1
Icons:
  '#':
    display:
      material: source:HDB:48130
      name: §9Axolotl
只要是包含头颅数据库的，全部消失

**Comment by xiaoluofa** [comment]
注意到上周有个更新，已经测试，没有修复，bug还在

**Comment by xiaoluofa** [comment]
@TheFloodDragon

**Comment by Dreeam-qwq** [comment]
Duplicated with https://github.com/Dreeam-qwq/TrMenu/issues/13

btw, this is an issue of Taboolib
