### ISSUE TITLE
[问题]: java17以下无法使用3.3.3a版本

### ISSUE THREAD

**Issue by polang233** [CoderKuo/TrMenu#86]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

···

### 🔍 详细的描述

1.12.2paper
java11

### 🗄 服务端日志

[22:00:21 ERROR]: Could not load 'plugins\TrMenu-3.3.3a.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 6 more
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 55
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:148) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:136) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:237) ~[patched_1.12.2.jar:git-Paper-1620]
        at me.arasple.mc.trmenu.taboolib.library.reflex.ClassAnalyser.analyseByASM(ClassAnalyser.kt:42) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.library.reflex.ClassAnalyser.analyse(ClassAnalyser.kt:21) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass$Companion.of(ReflexClass.kt:73) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass$Companion.of(ReflexClass.kt:66) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.io.ProjectScannerKt.getInstance(ProjectScanner.kt:156) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:102) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:77) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.lambda$init$0(VisitorHandler.java:44) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.TabooLib$1.run(TabooLib.java:79) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:56) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.TabooLib.lifeCycle(TabooLib.java:56) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:53) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 6 more

### ⚙ 配置文件

```

```

**Comment by TheFloodDragon** [comment]
Try to use the latest **Action's Build**

Here's the link: https://github.com/Dreeam-qwq/TrMenu/actions/runs/10162871420

**Comment by polang233** [comment]
> Try to use the latest **Action's Build**
> 
> Here's the link: https://github.com/Dreeam-qwq/TrMenu/actions/runs/10162871420

加载时出现如下报错:
`[12:22:13 ERROR]: Could not load 'plugins\TrMenu-3.3.3a.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 6 more
Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:69) ~[patched_1.12.2.jar:git-Paper-1620]
        at me.arasple.mc.trmenu.taboolib.library.reflex.asm.AsmClassVisitor.<init>(AsmClassVisitor.kt:11) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.library.reflex.ClassAnalyser.analyseByASM(ClassAnalyser.kt:43) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.library.reflex.ClassAnalyser.analyse(ClassAnalyser.kt:21) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass$Companion.of(ReflexClass.kt:73) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass$Companion.of(ReflexClass.kt:66) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.io.ProjectScannerKt.getInstance(ProjectScanner.kt:156) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:102) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:77) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.lambda$init$0(VisitorHandler.java:44) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.TabooLib$1.run(TabooLib.java:79) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:56) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.TabooLib.lifeCycle(TabooLib.java:56) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:53) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 6 more`

**Comment by aeroidesdev** [comment]
历史原因,试试最新版

**Comment by polang233** [comment]
https://github.com/Dreeam-qwq/TrMenu/pull/108
已解决
