### ISSUE TITLE
[Bug]: 1.21.1 support

### ISSUE THREAD

**Issue by Mapacheee** [CoderKuo/TrMenu#93]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

```
TrMenu Dump Information

  | Server OS: Windows 10
  | Server software: Paper
  | Java version: 21 temurin

  | TabooLib: Lastest at the moment
  | TrMenu: Lastest at the moment
```

### 🔍 Detailed description

```
1. Installing TrMenu
```

### 🗄 Server log

```
[12:00:36 INFO]: [TrMenu] Loading server plugin TrMenu v3.3.3a
[12:00:36 WARN]: me.arasple.mc.trmenu.taboolib.common.inject.ClassVisitException: class me.arasple.mc.trmenu.taboolib.module.nms.MinecraftVersion#init: VisitorGroup{priority=0, list=[AwakeFunction(lifeCycle=NONE), AwakeFunction(lifeCycle=CONST), AwakeFunction(lifeCycle=INIT), AwakeFunction(lifeCycle=LOAD), AwakeFunction(lifeCycle=ENABLE), AwakeFunction(lifeCycle=ACTIVE), AwakeFunction(lifeCycle=DISABLE), me.arasple.mc.trmenu.taboolib.common.platform.command.SimpleCommandRegister@40577f47, me.arasple.mc.trmenu.taboolib.platform.compat.PlaceholderExpansion$PlaceholderRegister@230c0433, me.arasple.mc.trmenu.taboolib.module.kether.KetherLoader@255ac19]} (LOAD)
[12:00:36 WARN]:        at TrMenu-3.3.3a.jar//me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:146)
[12:00:36 WARN]:        at TrMenu-3.3.3a.jar//me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:114)
[12:00:36 WARN]:        at TrMenu-3.3.3a.jar//me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:77)
[12:00:36 WARN]:        at TrMenu-3.3.3a.jar//me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.lambda$init$0(VisitorHandler.java:44)
[12:00:36 WARN]:        at TrMenu-3.3.3a.jar//me.arasple.mc.trmenu.taboolib.common.TabooLib$1.run(TabooLib.java:79)
[12:00:36 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[12:00:36 WARN]:        at TrMenu-3.3.3a.jar//me.arasple.mc.trmenu.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:56)
[12:00:36 WARN]:        at java.base/java.util.Optional.ifPresent(Optional.java:178)
[12:00:36 WARN]:        at TrMenu-3.3.3a.jar//me.arasple.mc.trmenu.taboolib.common.TabooLib.lifeCycle(TabooLib.java:56)
[12:00:36 WARN]:        at TrMenu-3.3.3a.jar//me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.onLoad(BukkitPlugin.java:73)
[12:00:36 WARN]:        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
[12:00:36 WARN]:        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
[12:00:36 WARN]:        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[12:00:36 WARN]:        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
[12:00:36 WARN]:        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:564)
[12:00:36 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:334)
[12:00:36 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226)
[12:00:36 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[12:00:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:00:36 WARN]: Caused by: java.lang.IllegalStateException: Unsupported Minecraft version, plugin disabled
[12:00:36 WARN]:        at TrMenu-3.3.3a.jar//me.arasple.mc.trmenu.taboolib.module.nms.MinecraftVersion.init(MinecraftVersion.kt:211)
[12:00:36 WARN]:        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
[12:00:36 WARN]:        at TrMenu-3.3.3a.jar//me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[12:00:36 WARN]:        at TrMenu-3.3.3a.jar//me.arasple.mc.trmenu.taboolib.common.platform.AwakeFunction.visit(AwakeFunction.kt:13)
[12:00:36 WARN]:        at TrMenu-3.3.3a.jar//me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:144)
[12:00:36 WARN]:        ... 18 more
```

### ⚙ Configurations

```
Anyone
```

Thanks for take ur time 🙏

**Comment by TheFloodDragon** [comment]
Already exist.

Please see [71](https://github.com/Dreeam-qwq/TrMenu/issues/71).
