### ISSUE TITLE
[问题]: 最新3.3.3a版本在 1.12.2 上无法正常加载插件

### ISSUE THREAD

**Issue by MelodyYuuka** [CoderKuo/TrMenu#97]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
无法加载插件


/version
This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

插件 (24): BedWarsProxy (${gitVer}1.2.4), CMI (9.7.5.0), CMILib (1.5.1.0), Citizens (2.0.32-SNAPSHOT (build 3170)), LastLoginAPI (1.7.4), LuckPerms (5.4.139), MarriageMaster (2.7.6-Release), MusicBox (2.1.0), NoteBlockAPI (1.6.2), Parties (3.2.13), PlaceholderAPI (2.11.6), Plan (5.6 build 2883), ServerUtils (3.5.4), SkinsRestorer (15.4.1), SuperLobby (4.7.4), TAB-Bridge (5.0.6), TrChat (2.1.0), TrMenu (3.3.1), UltimateAutoRestart (2024.06-a), Vault (1.7.3-CMI), ViaVersion (5.0.3), VoidGen (2.2.1), WorldEdit (6.1.9;caf0ad9) 和 ajLeaderboards (2.9.0)
```

### 🔍 详细的描述

3.3.3a版本在1.12.2上无法加载插件，3.3.1版本可以正常加载使用

### 🗄 服务端日志

```
[11:51:25 ERROR]: Could not load 'plugins/TrMenu-3.3.3a.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 6 more
Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:69) ~[patched_1.12.2.jar:git-Paper-1620]
        at me.arasple.mc.trmenu.taboolib.library.reflex.asm.AsmClassVisitor.<init>(AsmClassVisitor.kt:11) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.library.reflex.ClassAnalyser.analyseByASM(ClassAnalyser.kt:43) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.library.reflex.ClassAnalyser.analyse(ClassAnalyser.kt:21) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass$Companion.of(ReflexClass.kt:73) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass$Companion.of(ReflexClass.kt:66) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.io.ProjectScannerKt.getInstance(ProjectScanner.kt:156) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:102) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:77) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.lambda$init$0(VisitorHandler.java:44) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.TabooLib$1.run(TabooLib.java:79) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:56) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.TabooLib.lifeCycle(TabooLib.java:56) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:53) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 6 more
```

**Comment by polang233** [comment]
https://github.com/Dreeam-qwq/TrMenu/issues/86
也是1.12.2

**Comment by aeroidesdev** [comment]
fix?
try latest version
